# Generated by Django 3.2.5 on 2021-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210725_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remuser',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='remuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='remrole',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='first_login',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='remuser',
            name='status',
        ),
        migrations.AlterField(
            model_name='remorganization',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remorganization',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remorganization',
            name='updated_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remorganization',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remrole',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remrole',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remrole',
            name='updated_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remrole',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remuser',
            name='created_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remuser',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remuser',
            name='updated_by',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remuser',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
