# Generated by Django 3.2.5 on 2021-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210813_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='nursery_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
