# Generated by Django 3.2.5 on 2021-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_nursery_nursery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantation',
            name='certified',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='certified_by',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='certified_date',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='owner_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='plantation_address',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='plantation_age',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='website',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='season',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='plantation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='yieldhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
