# Generated by Django 3.2.5 on 2021-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_total_number_tress_beninyield_total_number_trees'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteiaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_code', models.CharField(max_length=200, unique=True)),
                ('cashew_tree_cover', models.FloatField(null=True)),
            ],
        ),
    ]
