# Generated by Django 3.2.5 on 2021-11-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_communesatellite_deptsatellite_specialtuple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communesatellite',
            old_name='cashew_tree_cover',
            new_name='cashew_tree_cover_comm',
        ),
        migrations.RenameField(
            model_name='communesatellite',
            old_name='commune',
            new_name='commune_comm',
        ),
        migrations.RenameField(
            model_name='communesatellite',
            old_name='country',
            new_name='country_comm',
        ),
        migrations.RenameField(
            model_name='communesatellite',
            old_name='department',
            new_name='department_comm',
        ),
        migrations.RenameField(
            model_name='deptsatellite',
            old_name='cashew_tree_cover',
            new_name='cashew_tree_cover_dept',
        ),
        migrations.RenameField(
            model_name='deptsatellite',
            old_name='country',
            new_name='country_dept',
        ),
        migrations.RenameField(
            model_name='deptsatellite',
            old_name='department',
            new_name='department_dept',
        ),
    ]
