# Generated by Django 3.2.5 on 2021-11-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20211109_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communesatellite',
            old_name='cashew_tree_cover_comm',
            new_name='cashew_tree_cover',
        ),
        migrations.RenameField(
            model_name='communesatellite',
            old_name='commune_comm',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='communesatellite',
            old_name='country_comm',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='communesatellite',
            old_name='department_comm',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='deptsatellite',
            old_name='cashew_tree_cover_dept',
            new_name='cashew_tree_cover',
        ),
        migrations.RenameField(
            model_name='deptsatellite',
            old_name='country_dept',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='deptsatellite',
            old_name='department_dept',
            new_name='department',
        ),
    ]
