# Generated by Django 3.2.5 on 2021-11-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20211110_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YieldHistory',
        ),
    ]
